language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
env:
  global:
    # Doctr deploy key for NSLS-II/NSLS-II.github.io
    - secure: "evmeG5/HUR9o9XizCvjl9hnX78eCQTMDpZuZw4i/9BOXz3abYXYX5Hf+E9Zm22HWBe0L+TP7C9+LpjIxhUJt9GNX4Z517W0d+ny1zNqepjFE4zTIfurkKdlDrE3Xp68Bt+5NMY0gSOxiIevXgXbNvQDqFPeejekTnygBoMO7tv7+WW2X1G6UWYs45uY7q2f8tuQUJW1e+eZ3v2s+/8JOifFYQg1Em+xqkBF21OGdoEBgnTMKXYFeAfpXFPjVUnoJ70OJSex4CzEm9oVEF2SR8r9oOlRnBAgH2TPE+e+lLWijeH8FZ0rvGyFTjjfHVv01iiDosFGIXXX6cLPeDuMiyRRgy/9pYCI8naKAbGPQKpNRR5WDNVnRWJNkngD3nmj7IFyISQyl+0naWDM60JkvHG60zwCov4bmE9Sk5npyH5oDgOa17yILSuHkVzg9NKqLuN+h+fYUmlmWm18rifxICkbqI/p9LZIkXmW3DyLNhuoEsGnIRdgCyXamC/5s9diJOuuTAPUhn838HPkxx1pT6pgtOz6hL+N8b0J70B9qzwzzOHfMWU3gGIojNSWR8nCwloczEKwPg5+sRI5w7qkoN90T+o7BuI15GSTn7MLD6+8C9AvqaVTkp11lulOU2NFAz7NOIHcGZuAOyPoKCp/TcFhHBli8a88t83xImzELc4o="

install:
  - pip install -r requirements.txt

script:
  - set -e
  - ./run_cookiecutter_example.py
  - pip install -e example/
  - ./copy_user_content.sh
  - pytest example/
  - make -C docs html
  - pip install doctr
  - doctr deploy --key-path github_deploy_key_nsls_ii_nsls_ii_github_io.enc --built-docs docs/build/html/ --deploy-repo NSLS-II/NSLS-II.github.io scientific-python-cookiecutter
