language: python
python:
  - 3.6
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
env:
  global:
    # Doctr deploy key for NSLS-II/NSLS-II.github.io
    - secure: "dipvlKqb4frhL0FJZ8X86kykBe4y7LypIuAt86V8YM+6iFuOZeipjaTtsbULUL6oAXTLDeTM19SGpGXsDVyo2yaTWxwk1/aBC1k5nDxjOqF0L0m0Q2F7XcShvZD7sjI3KNfFiBKINewTD5cGzqM5Okl8EdC9Y/Igdul9DxEEIZWQLPplsNyepkLeIEZMSRKkaBKJOssrrGVOgJE4N0BuB6Axm8Uf75XMiQunHB7y7jJ+JTlYHpdqpewVyvNbQvoHf6chcX+rADoRqwNoCMA1QTo8cCVl9gjlPRWeQb2iNVgxwndSIJhgM80H39DyikTNV90JzJUSVF7PPX6qZU+Y+r6eI4Bo73Ev3sxkDDBMMmKfGOtZ+XWQFamWu/MuM4VMdCLUwK4c9CpgAkFe1UQ6xUqFJgww079YdLLyrW+I0kZnYyjSrNXds+vH2gP+jvXYU8Pej5XMm5vqcmF71FTWZdySFlB1YPSGhiSBl8Z17y3nshhq/u5buJbEtS5UZIq6oZ/waV6NuLbx6goii9a9BgG8pZN220BgF2RymVvsN7ETGLyQsL5WmvcyiIuUG1jg+mEOTTzpSB4yTjC1EgOVpRiHMunk26HtmkycZbf/EmyZK8XuCrpQP5peCequXa2TXoIJqGWB0RS93kyARQa8mHZA1cylez12qR3C8gwxjkY="

install:
  - pip install -r requirements.txt

script:
  - set -e
  - make -C docs html
  - pip install doctr
  - doctr deploy --built-docs docs/build/html/ --deploy-repo NSLS-II/NSLS-II.github.io packaging-sicentific-python
