name: Docs

on:
  push:
  pull_request:


jobs:
  publish-docs:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set environment variable
        run: |
          export REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}  # just the repo, as opposed to org/repo
          echo "REPOSITORY_NAME=${REPOSITORY_NAME}" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install 
        shell: bash
        run: |
          pip install -r requirements.txt
          sphinx-build -b html docs/source build

      - name: Deploy Website
        uses: peaceiris/actions-gh-pages@v3
          pip install -r requirements.txt
          ./run_cookiecutter_example.py

          # Test the style with pre-commit
          cd example/
          git config --global user.name "CI Tester"
          git config --global user.email "noreply@github.com"
          git init
          git add .
          git commit -m "Initial commit"
          pre-commit run --all-files
          cd ..

          pip install -e example/
          ./copy_user_content.sh
          pytest example/
            
      - name: Build docs
        run: make -C docs html

      - uses: actions/upload-artifact@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
